// Generated by gencpp from file ximea_camera/XimeaCamSensorMsg.msg
// DO NOT EDIT!


#ifndef XIMEA_CAMERA_MESSAGE_XIMEACAMSENSORMSG_H
#define XIMEA_CAMERA_MESSAGE_XIMEACAMSENSORMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ximea_camera
{
template <class ContainerAllocator>
struct XimeaCamSensorMsg_
{
  typedef XimeaCamSensorMsg_<ContainerAllocator> Type;

  XimeaCamSensorMsg_()
    : header()
    , exposure_time(0.0)
    , gain(0)
    , temperature(0.0)  {
    }
  XimeaCamSensorMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , exposure_time(0.0)
    , gain(0)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _exposure_time_type;
  _exposure_time_type exposure_time;

   typedef uint8_t _gain_type;
  _gain_type gain;

   typedef float _temperature_type;
  _temperature_type temperature;




  typedef boost::shared_ptr< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> const> ConstPtr;

}; // struct XimeaCamSensorMsg_

typedef ::ximea_camera::XimeaCamSensorMsg_<std::allocator<void> > XimeaCamSensorMsg;

typedef boost::shared_ptr< ::ximea_camera::XimeaCamSensorMsg > XimeaCamSensorMsgPtr;
typedef boost::shared_ptr< ::ximea_camera::XimeaCamSensorMsg const> XimeaCamSensorMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ximea_camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ximea_camera': ['/home/odroid/ros_workspace/src/ximea_camera/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddb3846a213c808208d6e9d94615a2f5";
  }

  static const char* value(const ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xddb3846a213c8082ULL;
  static const uint64_t static_value2 = 0x08d6e9d94615a2f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ximea_camera/XimeaCamSensorMsg";
  }

  static const char* value(const ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 exposure_time\n\
uint8 gain\n\
float32 temperature\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.exposure_time);
      stream.next(m.gain);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct XimeaCamSensorMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ximea_camera::XimeaCamSensorMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "exposure_time: ";
    Printer<float>::stream(s, indent + "  ", v.exposure_time);
    s << indent << "gain: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gain);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XIMEA_CAMERA_MESSAGE_XIMEACAMSENSORMSG_H
